-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ) AS A JOIN REST_INFO AS B USING (FOOD_TYPE, FAVORITES)
ORDER BY FOOD_TYPE DESC;